package capture

import "time"

// Platform identifies the device operating system. Only iOS is supported in
// M1; the type exists so the model stays platform-neutral (G5).
type Platform string

const (
	// PlatformIOS is the iOS platform.
	PlatformIOS Platform = "ios"
)

// ============================================================================
// Device
// ============================================================================

// DeviceStatus is the connection status of a device as shown in the Web UI
// (requirement F1.2). It is a derived status, not a persisted field: it is
// computed from the device's last heartbeat and the presence of an active
// capture session.
type DeviceStatus string

const (
	// DeviceStatusIdle means the device is registered but has no active
	// capture session (待命): no capture, no mocking.
	DeviceStatusIdle DeviceStatus = "idle"
	// DeviceStatusCapturing means the device has an active capture session
	// (抓包中): it is uploading traffic and executing mock rules.
	DeviceStatusCapturing DeviceStatus = "capturing"
	// DeviceStatusOffline means no heartbeat was received within the timeout
	// (离线): the capture session, if any, has been ended.
	DeviceStatusOffline DeviceStatus = "offline"
)

// Device is a running instance of an app on a single physical device (or
// simulator). It is uniquely identified by (App, Did).
//
// Did is generated by the SDK and scoped to the app: different apps may
// generate the same did, so the full device identifier is always (App, Did)
// (requirement 决策 #2/#7).
type Device struct {
	// App is the application identifier (e.g. bundle id).
	App string `json:"app"`
	// Did is the device identifier generated by the SDK.
	Did string `json:"did"`
	// Name is an optional custom name set from the Web UI ("张三的 15 Pro").
	Name string `json:"name,omitempty"`
	// Platform is the OS platform (ios for M1).
	Platform Platform `json:"platform,omitempty"`
	// OSVersion is the OS version reported at registration.
	OSVersion string `json:"osVersion,omitempty"`
	// SDKVersion is the MockNetPack SDK version.
	SDKVersion string `json:"sdkVersion,omitempty"`
	// AppVersion is the app version.
	AppVersion string `json:"appVersion,omitempty"`
	// LastSeenAt is the time of the last heartbeat (zero if never seen).
	LastSeenAt time.Time `json:"lastSeenAt"`
	// RegisteredAt is when the device first registered.
	RegisteredAt time.Time `json:"registeredAt"`
}

// DeriveDeviceStatus computes the device status for API output.
//
// Priority: heartbeat timeout (offline) > active capture session (capturing)
// > otherwise idle. Offline is checked first because a session is ended when
// the heartbeat times out; checking it first also covers the small window
// before the periodic sweep cleans up the stale session.
func DeriveDeviceStatus(lastSeenAt, now time.Time, timeout time.Duration, hasActiveSession bool) DeviceStatus {
	if now.Sub(lastSeenAt) > timeout {
		return DeviceStatusOffline
	}
	if hasActiveSession {
		return DeviceStatusCapturing
	}
	return DeviceStatusIdle
}

// DeviceView is the API output shape for a device (contract Device schema):
// the persisted Device fields plus the derived Status and the active capture
// session (if any). It is computed by the capture manager on read; the status
// is never a persisted field.
type DeviceView struct {
	*Device
	// Status is the derived connection status (offline > capturing > idle).
	Status DeviceStatus `json:"status"`
	// CurrentSession is the active capture session, if any.
	CurrentSession *CaptureSession `json:"currentSession,omitempty"`
}

// ============================================================================
// Capture Session
// ============================================================================

// SessionStatus is the lifecycle status of a capture session (requirement
// 6.6: 待命 / 抓包中 / 结束). "Idle" is not a session state — a session only
// exists once activated; idle is the device state without a session.
type SessionStatus string

const (
	// SessionStatusCapturing means the session is active: the SDK uploads
	// traffic and executes mock rules.
	SessionStatusCapturing SessionStatus = "capturing"
	// SessionStatusEnded means the session finished (page close / heartbeat
	// timeout / forced disconnect); temporary traffic has been cleared.
	SessionStatusEnded SessionStatus = "ended"
)

// CaptureSession is one capture period, activated from the Web UI and lasting
// until the last viewer closes the page, the device heartbeat times out, or
// it is forcibly ended. A device has at most one capturing session at a time.
type CaptureSession struct {
	// ID is a unique session identifier (ULID).
	ID string `json:"id"`
	// App is the app dimension of the owning device.
	App string `json:"app"`
	// Did is the device dimension of the owning device.
	Did string `json:"did"`
	// Status is the session lifecycle status.
	Status SessionStatus `json:"status"`
	// StartedAt is when the session was activated.
	StartedAt time.Time `json:"startedAt"`
	// EndedAt is when the session ended (nil while capturing).
	EndedAt *time.Time `json:"endedAt,omitempty"`
	// RequestCount is the number of traffic entries captured in this session.
	RequestCount int `json:"requestCount"`
	// ViewerCount is the number of Web pages currently viewing this session.
	// The session ends when the last viewer is released.
	ViewerCount int `json:"viewerCount"`
}

// Start marks the session as capturing. Idempotent: if the session is already
// capturing or ended, it is left unchanged.
func (s *CaptureSession) Start(now time.Time) {
	if s.Status == SessionStatusCapturing || s.Status == SessionStatusEnded {
		return
	}
	s.Status = SessionStatusCapturing
	if s.StartedAt.IsZero() {
		s.StartedAt = now
	}
}

// End marks the session as ended and records the end time. Idempotent: ending
// an already-ended session keeps the original EndedAt.
func (s *CaptureSession) End(now time.Time) {
	if s.Status == SessionStatusEnded {
		return
	}
	s.Status = SessionStatusEnded
	t := now
	s.EndedAt = &t
}

// ViewerLease is a page-level lease held by one Web page viewing a session.
// A viewer registers on page open, periodically renews (extending TTL), and
// releases on page close; the server also garbage-collects expired leases as
// a fallback because page-close events are not guaranteed to fire.
type ViewerLease struct {
	// ViewerID is a client-generated page-level UUID.
	ViewerID string `json:"viewerId"`
	// Label is an optional human-readable page label (debugging).
	Label string `json:"label,omitempty"`
	// TTLSeconds is the lease TTL granted by the server.
	TTLSeconds int `json:"ttlSeconds"`
	// ExpiresAt is when the lease expires if not renewed.
	ExpiresAt time.Time `json:"expiresAt"`
}

// ============================================================================
// Traffic
// ============================================================================

// TrafficEntry is the complete information of one HTTP request/response
// captured by the SDK (requirement F3.3). Fields follow mockd's
// requestlog.Entry as the blueprint. M1 defines the model only; ingestion and
// storage land in M2.
type TrafficEntry struct {
	// ID is a server-generated traffic record ID.
	ID string `json:"id,omitempty"`
	// SessionID is the capture session this traffic belongs to.
	SessionID string `json:"sessionId,omitempty"`
	// Timestamp is when the request was initiated (RFC3339).
	Timestamp time.Time `json:"timestamp"`
	// Method is the HTTP method.
	Method string `json:"method"`
	// URL is the full request URL.
	URL string `json:"url"`
	// Path is the URL path (used for mock matching).
	Path string `json:"path,omitempty"`
	// Query is the raw query string without '?', preserving original order.
	Query string `json:"query,omitempty"`
	// RequestHeaders are the request headers (multi-value).
	RequestHeaders map[string][]string `json:"requestHeaders,omitempty"`
	// RequestBody is the request body as UTF-8 text when decodable; otherwise
	// a "[binary N bytes]" display placeholder (see RequestBodyBase64).
	RequestBody string `json:"requestBody,omitempty"`
	// RequestBodyBase64 carries the raw request body bytes (base64) when it is
	// not UTF-8 text, so "Mock 此请求" can replay the exact original bytes.
	RequestBodyBase64 string `json:"requestBodyBase64,omitempty"`
	// StatusCode is the response status code (zero when the request failed).
	StatusCode int `json:"statusCode,omitempty"`
	// ResponseHeaders are the response headers (multi-value).
	ResponseHeaders map[string][]string `json:"responseHeaders,omitempty"`
	// ResponseBody is the response body as UTF-8 text when decodable; otherwise
	// a "[binary N bytes]" display placeholder (see ResponseBodyBase64).
	ResponseBody string `json:"responseBody,omitempty"`
	// ResponseBodyBase64 carries the raw response body bytes (base64) when it is
	// not UTF-8 text, so a rule can replay the exact original bytes (M3 fix).
	ResponseBodyBase64 string `json:"responseBodyBase64,omitempty"`
	// Error is the error message when the request failed.
	Error string `json:"error,omitempty"`
	// DurationMs is the request duration in milliseconds.
	DurationMs int `json:"durationMs"`
	// Mocked marks whether this request hit a mock rule (M3 onward; the Web
	// request stream labels it "Mock 命中").
	Mocked bool `json:"mocked,omitempty"`
}

// ============================================================================
// Server configuration
// ============================================================================

// ServerConfig carries heartbeat parameters pushed to the SDK at
// registration/heartbeat time. Both values are server-side configuration
// items (requirement 决策 #14, defaults 15~20s / 60s).
type ServerConfig struct {
	// HeartbeatIntervalSeconds is the interval the SDK should heartbeat at.
	HeartbeatIntervalSeconds int `json:"heartbeatIntervalSeconds"`
	// HeartbeatTimeoutSeconds is the threshold after which the server
	// considers the device offline and ends its capture session.
	HeartbeatTimeoutSeconds int `json:"heartbeatTimeoutSeconds"`
}

// ============================================================================
// Mock rules (M3)
// ============================================================================

// MockResponse is the canned response a MockRule returns when it matches
// (contract MockResponse). Headers are single-valued by design (the contract
// does not carry multi-value mock headers).
type MockResponse struct {
	StatusCode int               `json:"statusCode"`
	Headers    map[string]string `json:"headers,omitempty"`
	// Body is the canned response body as UTF-8 text.
	Body string `json:"body,omitempty"`
	// BodyBase64 carries the raw response bytes (base64) when the original body
	// was binary (e.g. application/xcp). When present the SDK replays these
	// exact bytes; Body is then only a display placeholder.
	BodyBase64 string `json:"bodyBase64,omitempty"`
}

// MockRuleSource is the persistent snapshot of the real request a rule was
// created from ("Mock 此请求"): the original request plus the real response
// b1. Temporary traffic is cleared at session end, but this snapshot persists
// with the rule so the original vs. mocked values can be reviewed later
// (requirement 6.6 / F3.4). A hand-authored rule (F4.1) has no source.
type MockRuleSource struct {
	Method          string              `json:"method"`
	Path            string              `json:"path"`
	URL             string              `json:"url,omitempty"`
	Query           string              `json:"query,omitempty"`
	RequestHeaders  map[string][]string `json:"requestHeaders,omitempty"`
	RequestBody     string              `json:"requestBody,omitempty"`
	RequestBodyBase64 string            `json:"requestBodyBase64,omitempty"`
	StatusCode      *int                `json:"statusCode,omitempty"`
	ResponseHeaders map[string][]string `json:"responseHeaders,omitempty"`
	ResponseBody    *string             `json:"responseBody,omitempty"`
	ResponseBodyBase64 string           `json:"responseBodyBase64,omitempty"`
	CapturedAt      time.Time           `json:"capturedAt"`
}

// MockRule is a persisted, device-scoped canned-response rule. It matches by
// Method + URL path (Query/Body ignored); while a capture session is active the
// SDK returns Response for matching requests. Enabled is the persisted user
// switch; the runtime Effective flag is computed at read time (MockRuleView)
// so an abnormal multi-enabled interface does not mock at all.
type MockRule struct {
	ID        string          `json:"id"`
	App       string          `json:"app"`
	Did       string          `json:"did"`
	Method    string          `json:"method"`
	Path      string          `json:"path"`
	Response  MockResponse    `json:"response"`
	Enabled   bool            `json:"enabled"`
	Source    *MockRuleSource `json:"source,omitempty"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	// LastUsedAt is the sliding-window cleanup baseline (M4, F8.3/决策15).
	// Refreshed when the rule is hit, edited via Web, or toggled on/off;
	// heartbeats, version polling and passive browsing do not refresh it.
	// Rules older than the retention (default 7 days, config item) are purged
	// with their source snapshot. A zero value (legacy rows pre-M4) is treated
	// as UpdatedAt by the janitor.
	LastUsedAt time.Time `json:"lastUsedAt"`
}

// MockRuleInput is the create/update payload (contract MockRuleInput).
type MockRuleInput struct {
	Method   string          `json:"method"`
	Path     string          `json:"path"`
	Response MockResponse    `json:"response"`
	Enabled  bool            `json:"enabled"`
	Source   *MockRuleSource `json:"source,omitempty"`
}

// MockRuleView is the API output for a MockRule: the persisted rule plus the
// server-computed runtime Effective flag. The SDK applies only Effective rules.
type MockRuleView struct {
	*MockRule
	// Effective is true only when this rule is the sole enabled rule for its
	// interface. In the abnormal multi-enabled state every rule on that
	// interface is Effective=false and reported in conflicts.
	Effective bool `json:"effective"`
}

// MockRuleConflict reports an abnormal state where more than one enabled rule
// exists for the same interface; the whole interface is not mocked and Web shows
// a popup (requirement 6.5 / F4.6).
type MockRuleConflict struct {
	Method  string `json:"method"`
	Path    string `json:"path"`
	Message string `json:"message"`
}
